-- ═══════════════════════════════════════════════════════
-- Affilite-Mix — Schema (matches live Supabase DB)
-- ═══════════════════════════════════════════════════════

-- SITES — master registry
-- id is a UUID auto-generated by Supabase; slug is the text identifier used in config/code.
CREATE TABLE sites (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug        text NOT NULL UNIQUE,
  name        text NOT NULL,
  domain      text NOT NULL DEFAULT '',
  language    text NOT NULL DEFAULT 'en',
  direction   text NOT NULL DEFAULT 'ltr',
  is_active   boolean DEFAULT true,

  -- Monetization
  monetization_type text DEFAULT 'affiliate'
                    CHECK (monetization_type IN ('affiliate', 'ads', 'both')),
  est_revenue_per_click numeric DEFAULT 0.35,
  ad_config   jsonb DEFAULT '{}',

  -- Theming
  theme       jsonb DEFAULT '{}',
  logo_url    text,
  favicon_url text,

  -- Navigation
  nav_items   jsonb DEFAULT '[]',
  footer_nav  jsonb DEFAULT '[]',

  -- Features
  features    jsonb DEFAULT '{"newsletter": true, "giftFinder": false, "search": true}',

  -- SEO
  meta_title       text,
  meta_description text,
  og_image_url     text,

  -- Social links
  social_links jsonb DEFAULT '{}',

  -- Custom CSS overrides
  custom_css  text,

  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

-- CATEGORIES
CREATE TABLE categories (
  id             uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id        uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name           text NOT NULL,
  slug           text NOT NULL,
  description    text DEFAULT '',
  taxonomy_type  text NOT NULL DEFAULT 'general'
                 CHECK (taxonomy_type IN ('general', 'budget', 'occasion', 'recipient', 'brand')),
  created_at     timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- PRODUCTS
CREATE TABLE products (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id       uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name          text NOT NULL,
  slug          text NOT NULL,
  description   text DEFAULT '',
  affiliate_url text DEFAULT '',
  image_url     text DEFAULT '',
  image_alt     text DEFAULT '',
  price         text DEFAULT '',
  price_amount  numeric,
  price_currency text DEFAULT 'USD',
  merchant      text DEFAULT '',
  score         real CHECK (score >= 0 AND score <= 10),
  featured      boolean DEFAULT false,
  status        text NOT NULL DEFAULT 'active'
                CHECK (status IN ('draft', 'active', 'archived')),
  category_id   uuid REFERENCES categories(id) ON DELETE SET NULL,
  cta_text      text DEFAULT '',
  deal_text     text DEFAULT '',
  deal_expires_at timestamptz,
  pros          text DEFAULT '',
  cons          text DEFAULT '',
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- CONTENT
CREATE TABLE content (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  title       text NOT NULL,
  slug        text NOT NULL,
  body        text DEFAULT '',
  excerpt     text DEFAULT '',
  featured_image text DEFAULT '',
  type        text NOT NULL DEFAULT 'article'
              CHECK (type IN (
                'article', 'review', 'comparison', 'guide', 'blog'
              )),
  status      text NOT NULL DEFAULT 'draft'
              CHECK (status IN ('draft', 'review', 'published', 'scheduled', 'archived')),
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  tags        text[] DEFAULT '{}',
  author      text,
  publish_at  timestamptz,
  meta_title  text,
  meta_description text,
  og_image    text,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- CONTENT <-> PRODUCTS (many-to-many)
CREATE TABLE content_products (
  content_id  uuid NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  product_id  uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  role        text DEFAULT 'hero'
              CHECK (role IN ('hero', 'featured', 'related', 'vs-left', 'vs-right')),
  PRIMARY KEY (content_id, product_id)
);

-- NEWSLETTER SUBSCRIBERS
CREATE TABLE newsletter_subscribers (
  id                  uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id             uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  email               text NOT NULL,
  status              text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'active', 'unsubscribed')),
  confirmation_token  text,
  confirmed_at        timestamptz,
  unsubscribe_token   uuid UNIQUE DEFAULT gen_random_uuid(),
  created_at          timestamptz DEFAULT now(),
  UNIQUE(site_id, email)
);

-- AFFILIATE CLICK TRACKING
CREATE TABLE affiliate_clicks (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id         uuid REFERENCES sites(id) ON DELETE SET NULL,
  product_name    text DEFAULT '',
  affiliate_url   text DEFAULT '',
  content_slug    text DEFAULT '',
  referrer        text DEFAULT '',
  created_at      timestamptz DEFAULT now()
);

-- SCHEDULED JOBS — ledger for all scheduled operations
CREATE TABLE scheduled_jobs (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  job_type    text NOT NULL
              CHECK (job_type IN ('publish_content', 'activate_product', 'archive_content', 'archive_product', 'custom')),
  target_id   uuid NOT NULL,
  scheduled_for timestamptz NOT NULL,
  status      text NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending', 'executed', 'failed', 'cancelled')),
  payload     jsonb DEFAULT '{}',
  executed_at timestamptz,
  error       text,
  created_at  timestamptz DEFAULT now()
);

-- ADMIN USERS — per-user admin accounts
CREATE TABLE admin_users (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email           text NOT NULL UNIQUE,
  password_hash   text NOT NULL,
  name            text NOT NULL DEFAULT '',
  role            text NOT NULL DEFAULT 'admin'
                  CHECK (role IN ('admin', 'super_admin')),
  is_active       boolean NOT NULL DEFAULT true,
  reset_token     text,
  reset_token_expires_at timestamptz,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- PAGES — custom static pages per niche (About, FAQ, etc.)
CREATE TABLE pages (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id       uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  slug          text NOT NULL,
  title         text NOT NULL,
  body          text DEFAULT '',
  is_published  boolean DEFAULT false,
  sort_order    integer DEFAULT 0,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- AD PLACEMENTS — monetization for niches with ad support
CREATE TABLE ad_placements (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id         uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name            text NOT NULL,
  placement_type  text NOT NULL CHECK (placement_type IN ('sidebar', 'in_content', 'header', 'footer', 'between_posts')),
  provider        text NOT NULL CHECK (provider IN ('adsense', 'carbon', 'ethicalads', 'custom')),
  ad_code         text,
  config          jsonb DEFAULT '{}',
  is_active       boolean DEFAULT true,
  priority        integer DEFAULT 0,
  created_at      timestamptz DEFAULT now()
);

-- AD IMPRESSIONS — basic tracking for ad performance
CREATE TABLE ad_impressions (
  id                uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id           uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  ad_placement_id   uuid NOT NULL REFERENCES ad_placements(id) ON DELETE CASCADE,
  page_path         text,
  impression_date   date DEFAULT CURRENT_DATE,
  count             integer DEFAULT 1,
  created_at        timestamptz DEFAULT now()
);

-- SHARED CONTENT — cross-niche content sharing
CREATE TABLE shared_content (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content_id      uuid NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  source_site_id  uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  target_site_id  uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  created_at      timestamptz DEFAULT now(),
  UNIQUE(content_id, target_site_id)
);

-- ═══════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════

CREATE INDEX idx_categories_site        ON categories(site_id);
CREATE INDEX idx_categories_taxonomy    ON categories(site_id, taxonomy_type);
CREATE INDEX idx_products_site          ON products(site_id);
CREATE INDEX idx_products_site_slug     ON products(site_id, slug);
CREATE INDEX idx_products_site_featured ON products(site_id, featured)
  WHERE featured = true;
CREATE INDEX idx_content_site           ON content(site_id);
CREATE INDEX idx_content_site_status    ON content(site_id, status);
CREATE INDEX idx_content_site_slug      ON content(site_id, slug);
CREATE INDEX idx_content_site_type      ON content(site_id, type);
CREATE INDEX idx_content_site_status_type ON content(site_id, status, type);
CREATE INDEX idx_content_updated        ON content(site_id, updated_at DESC)
  WHERE status = 'published';
CREATE INDEX idx_clicks_site            ON affiliate_clicks(site_id);
CREATE INDEX idx_clicks_created         ON affiliate_clicks(created_at DESC);
CREATE INDEX idx_newsletter_site        ON newsletter_subscribers(site_id);
CREATE INDEX idx_newsletter_site_email  ON newsletter_subscribers(site_id, email);
CREATE INDEX idx_scheduled_jobs_site    ON scheduled_jobs(site_id);
CREATE INDEX idx_scheduled_jobs_pending ON scheduled_jobs(status, scheduled_for)
  WHERE status = 'pending';
CREATE INDEX idx_admin_users_email     ON admin_users(email);
CREATE INDEX idx_pages_site            ON pages(site_id);
CREATE INDEX idx_pages_site_slug       ON pages(site_id, slug);
CREATE INDEX idx_ad_placements_site    ON ad_placements(site_id);
CREATE INDEX idx_ad_impressions_site   ON ad_impressions(site_id);
CREATE INDEX idx_ad_impressions_date   ON ad_impressions(ad_placement_id, impression_date);
CREATE INDEX idx_shared_content_target ON shared_content(target_site_id);
CREATE INDEX idx_shared_content_source ON shared_content(source_site_id);

-- Full-text search indexes (GIN)
CREATE INDEX idx_content_fts_title   ON content USING gin (to_tsvector('simple', title));
CREATE INDEX idx_content_fts_excerpt ON content USING gin (to_tsvector('simple', excerpt));
CREATE INDEX idx_products_fts_name   ON products USING gin (to_tsvector('simple', name));
CREATE INDEX idx_products_fts_desc   ON products USING gin (to_tsvector('simple', description));

-- ═══════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════

ALTER TABLE sites             ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE products          ENABLE ROW LEVEL SECURITY;
ALTER TABLE content           ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_products  ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks  ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_jobs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE pages                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_placements         ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_impressions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_content        ENABLE ROW LEVEL SECURITY;

-- Public read policies (anon key)
CREATE POLICY "public_read_sites"
  ON sites FOR SELECT USING (is_active = true);

CREATE POLICY "public_read_categories"
  ON categories FOR SELECT
  USING (EXISTS (SELECT 1 FROM sites WHERE sites.id = categories.site_id AND sites.is_active = true));

CREATE POLICY "public_read_active_products"
  ON products FOR SELECT USING (status = 'active');

CREATE POLICY "public_read_published_content"
  ON content FOR SELECT USING (status = 'published');

CREATE POLICY "public_read_content_products"
  ON content_products FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM content c
      WHERE c.id = content_products.content_id AND c.status = 'published'
    )
  );

-- Anonymous write policies (public actions) — validate site_id exists
CREATE POLICY "public_insert_clicks"
  ON affiliate_clicks FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM sites WHERE sites.id = affiliate_clicks.site_id));

CREATE POLICY "public_insert_newsletter"
  ON newsletter_subscribers FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM sites WHERE sites.id = newsletter_subscribers.site_id));

-- Service-role policies (defense-in-depth, scoped to service_role)
CREATE POLICY "service_full_access_categories"
  ON categories FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_products"
  ON products FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_content"
  ON content FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_content_products"
  ON content_products FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_clicks"
  ON affiliate_clicks FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_newsletter"
  ON newsletter_subscribers FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_scheduled_jobs"
  ON scheduled_jobs FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_admin_users"
  ON admin_users FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_pages"
  ON pages FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_ad_placements"
  ON ad_placements FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_ad_impressions"
  ON ad_impressions FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "service_full_access_shared_content"
  ON shared_content FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Public read: published pages are visible to the public
CREATE POLICY "public_read_published_pages"
  ON pages FOR SELECT USING (is_published = true);

-- Public insert: ad impressions can be recorded by the public
CREATE POLICY "public_insert_ad_impressions"
  ON ad_impressions FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM sites WHERE sites.id = ad_impressions.site_id));

-- Note: All admin operations use the Supabase service key (bypasses RLS).

-- ═══════════════════════════════════════════════════════
-- TRIGGERS
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER content_updated_at
  BEFORE UPDATE ON content
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER sites_updated_at
  BEFORE UPDATE ON sites
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ═══════════════════════════════════════════════════════
-- SEED: arabic-tools site
-- ═══════════════════════════════════════════════════════

INSERT INTO sites (slug, name, domain, language, direction)
VALUES ('arabic-tools', 'Arabic Tools', 'arabictools.wristnerd.xyz', 'ar', 'rtl');

-- ═══════════════════════════════════════════════════════
-- SEED: crypto-tools site
-- ═══════════════════════════════════════════════════════

INSERT INTO sites (slug, name, domain, language, direction)
VALUES ('crypto-tools', 'Crypto Tools', 'crypto.wristnerd.xyz', 'en', 'ltr');

-- Crypto categories
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO categories (site_id, name, slug) VALUES
  ((SELECT id FROM crypto), 'Exchanges', 'exchanges'),
  ((SELECT id FROM crypto), 'Wallets', 'wallets'),
  ((SELECT id FROM crypto), 'DeFi', 'defi'),
  ((SELECT id FROM crypto), 'Mining', 'mining'),
  ((SELECT id FROM crypto), 'NFTs', 'nfts'),
  ((SELECT id FROM crypto), 'Education', 'education');

-- Crypto products (UUIDs auto-generated; category_id resolved via slug)
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO products (site_id, name, slug, description, affiliate_url, image_url, price, merchant, score, featured, status, category_id) VALUES
  ((SELECT id FROM crypto), 'Binance', 'binance',
   'World''s largest crypto exchange by trading volume. Low fees and 350+ coins supported.',
   'https://www.binance.com/ref/example', '', 'Free to join', 'Binance', 9.2, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges')),
  ((SELECT id FROM crypto), 'Coinbase', 'coinbase',
   'Beginner-friendly US-based exchange with strong regulatory compliance.',
   'https://www.coinbase.com/ref/example', '', 'Free to join', 'Coinbase', 8.5, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges')),
  ((SELECT id FROM crypto), 'Ledger Nano X', 'ledger-nano-x',
   'Premium Bluetooth-enabled hardware wallet supporting 5,500+ coins.',
   'https://www.ledger.com/ref/example', '', '$149', 'Ledger', 9.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets')),
  ((SELECT id FROM crypto), 'Trezor Model T', 'trezor-model-t',
   'Open-source hardware wallet with touchscreen and advanced security features.',
   'https://www.trezor.io/ref/example', '', '$219', 'Trezor', 8.8, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets')),
  ((SELECT id FROM crypto), 'Aave', 'aave',
   'Leading DeFi lending protocol. Earn interest or borrow against your crypto.',
   'https://aave.com/ref/example', '', 'Free', 'Aave', 8.7, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'defi')),
  ((SELECT id FROM crypto), 'NiceHash', 'nicehash',
   'Marketplace for mining hash power. Mine or buy hash power easily.',
   'https://www.nicehash.com/ref/example', '', 'Free', 'NiceHash', 7.5, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'mining')),
  ((SELECT id FROM crypto), 'OpenSea', 'opensea',
   'Largest NFT marketplace for buying, selling, and discovering digital assets.',
   'https://opensea.io/ref/example', '', 'Free', 'OpenSea', 8.0, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'nfts')),
  ((SELECT id FROM crypto), 'Kraken', 'kraken',
   'Established US exchange with advanced trading features and staking.',
   'https://www.kraken.com/ref/example', '', 'Free to join', 'Kraken', 8.6, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges'));

-- Crypto content
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO content (site_id, title, slug, body, excerpt, type, status, category_id, tags, author) VALUES
  ((SELECT id FROM crypto),
   'Best Crypto Exchanges in 2026: Complete Comparison',
   'best-crypto-exchanges-2026',
   '<h2>Top Crypto Exchanges Compared</h2><p>Choosing the right crypto exchange is one of the most important decisions for any trader.</p>',
   'Compare the top cryptocurrency exchanges by fees, security, and features.',
   'comparison', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges'),
   ARRAY['exchanges', 'comparison', 'trading'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'Ledger Nano X Review: Is It Worth the Price?',
   'ledger-nano-x-review',
   '<h2>Ledger Nano X Review</h2><p>The Ledger Nano X is one of the most popular hardware wallets on the market.</p>',
   'In-depth review of the Ledger Nano X hardware wallet.',
   'review', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets'),
   ARRAY['wallets', 'hardware-wallet', 'security'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'Beginner''s Guide to DeFi: What You Need to Know',
   'beginners-guide-to-defi',
   '<h2>What is DeFi?</h2><p>Decentralized Finance (DeFi) refers to financial services built on blockchain technology.</p>',
   'Learn the fundamentals of Decentralized Finance.',
   'guide', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'defi'),
   ARRAY['defi', 'guide', 'beginners'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'How to Choose a Crypto Wallet in 2026',
   'how-to-choose-crypto-wallet',
   '<h2>Choosing the Right Crypto Wallet</h2><p>Your crypto wallet is the gateway to the blockchain.</p>',
   'A comprehensive guide to choosing the best crypto wallet.',
   'article', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets'),
   ARRAY['wallets', 'security', 'guide'], 'CryptoTools Team');

-- ═══════════════════════════════════════════════════════
-- SEED: watch-tools site
-- ═══════════════════════════════════════════════════════

INSERT INTO sites (slug, name, domain, language, direction)
VALUES ('watch-tools', 'WristNerd', 'wristnerd.xyz', 'en', 'ltr');

-- Watch-tools taxonomy categories (budget)
WITH watch AS (SELECT id FROM sites WHERE slug = 'watch-tools')
INSERT INTO categories (site_id, name, slug, description, taxonomy_type) VALUES
  ((SELECT id FROM watch), 'Under $100', 'under-100', 'Great starter watches under $100', 'budget'),
  ((SELECT id FROM watch), 'Under $200', 'under-200', 'Sweet spot for gift watches under $200', 'budget'),
  ((SELECT id FROM watch), 'Under $300', 'under-300', 'Premium quality watches under $300', 'budget'),
  ((SELECT id FROM watch), 'Under $500', 'under-500', 'Luxury territory watches under $500', 'budget'),
  ((SELECT id FROM watch), '$500+', 'luxury-500-plus', 'The best of the best — luxury watches $500 and up', 'budget');

-- Watch-tools taxonomy categories (occasion)
WITH watch AS (SELECT id FROM sites WHERE slug = 'watch-tools')
INSERT INTO categories (site_id, name, slug, description, taxonomy_type) VALUES
  ((SELECT id FROM watch), 'Father''s Day', 'fathers-day', 'Perfect watches for Father''s Day gifts', 'occasion'),
  ((SELECT id FROM watch), 'Christmas', 'christmas', 'Top watch picks for Christmas gifting', 'occasion'),
  ((SELECT id FROM watch), 'Birthday', 'birthday', 'Birthday-worthy watches for every budget', 'occasion'),
  ((SELECT id FROM watch), 'Valentine''s Day', 'valentines-day', 'Romantic watch gifts for Valentine''s Day', 'occasion'),
  ((SELECT id FROM watch), 'Anniversary', 'anniversary', 'Celebrate milestones with a timeless watch', 'occasion'),
  ((SELECT id FROM watch), 'Graduation', 'graduation', 'Mark the achievement with a graduation watch', 'occasion');

-- Watch-tools taxonomy categories (recipient)
WITH watch AS (SELECT id FROM sites WHERE slug = 'watch-tools')
INSERT INTO categories (site_id, name, slug, description, taxonomy_type) VALUES
  ((SELECT id FROM watch), 'For Him', 'for-him', 'Watch gift guides curated for men', 'recipient'),
  ((SELECT id FROM watch), 'For Her', 'for-her', 'Watch gift guides curated for women', 'recipient'),
  ((SELECT id FROM watch), 'For Teens', 'for-teens', 'Stylish and affordable watches for teenagers', 'recipient');

-- Watch-tools taxonomy categories (brand)
WITH watch AS (SELECT id FROM sites WHERE slug = 'watch-tools')
INSERT INTO categories (site_id, name, slug, description, taxonomy_type) VALUES
  ((SELECT id FROM watch), 'Seiko', 'seiko', 'Seiko watches — Japanese craftsmanship since 1881', 'brand'),
  ((SELECT id FROM watch), 'Orient', 'orient', 'Orient watches — affordable mechanical excellence', 'brand'),
  ((SELECT id FROM watch), 'Tissot', 'tissot', 'Tissot watches — Swiss precision since 1853', 'brand'),
  ((SELECT id FROM watch), 'Hamilton', 'hamilton', 'Hamilton watches — American heritage, Swiss made', 'brand'),
  ((SELECT id FROM watch), 'Casio', 'casio', 'Casio watches — innovation and durability', 'brand');

-- Arabic-tools categories
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO categories (site_id, name, slug, description) VALUES
  ((SELECT id FROM arabic), 'أدوات الكتابة', 'writing-tools', 'أفضل أدوات الكتابة العربية والتحرير'),
  ((SELECT id FROM arabic), 'أدوات الترجمة', 'translation-tools', 'أدوات ترجمة احترافية للغة العربية'),
  ((SELECT id FROM arabic), 'أدوات التعليم', 'education-tools', 'منصات وأدوات تعلم اللغة العربية'),
  ((SELECT id FROM arabic), 'أدوات التصميم', 'design-tools', 'أدوات تصميم تدعم الخط العربي'),
  ((SELECT id FROM arabic), 'أدوات SEO', 'seo-tools', 'أدوات تحسين محركات البحث للمحتوى العربي');

-- Arabic-tools products
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO products (site_id, name, slug, description, affiliate_url, price, merchant, score, featured, status, category_id, cta_text) VALUES
  ((SELECT id FROM arabic), 'Grammarly Arabic', 'grammarly-arabic',
   'أداة تدقيق لغوي متقدمة تدعم اللغة العربية مع اقتراحات ذكية.',
   'https://www.grammarly.com/ref/example', 'مجاني / $12 شهرياً', 'Grammarly', 8.5, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'writing-tools'),
   'جرّب مجاناً'),
  ((SELECT id FROM arabic), 'DeepL Translator', 'deepl-translator',
   'أفضل مترجم آلي بالذكاء الاصطناعي مع دعم ممتاز للعربية.',
   'https://www.deepl.com/ref/example', 'مجاني / $8.74 شهرياً', 'DeepL', 9.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   'ترجم الآن'),
  ((SELECT id FROM arabic), 'Duolingo Arabic', 'duolingo-arabic',
   'تعلم اللغة العربية مجاناً مع دروس تفاعلية وممتعة.',
   'https://www.duolingo.com/ref/example', 'مجاني / $6.99 شهرياً', 'Duolingo', 8.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'education-tools'),
   'ابدأ التعلم'),
  ((SELECT id FROM arabic), 'Canva Arabic', 'canva-arabic',
   'منصة تصميم سهلة مع قوالب ودعم كامل للخط العربي.',
   'https://www.canva.com/ref/example', 'مجاني / $12.99 شهرياً', 'Canva', 9.2, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'design-tools'),
   'صمّم مجاناً'),
  ((SELECT id FROM arabic), 'Ahrefs', 'ahrefs',
   'أداة SEO احترافية لتحليل الكلمات المفتاحية والروابط الخلفية.',
   'https://ahrefs.com/ref/example', '$99 شهرياً', 'Ahrefs', 9.1, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'seo-tools'),
   'جرّب Ahrefs'),
  ((SELECT id FROM arabic), 'Google Translate', 'google-translate',
   'خدمة ترجمة مجانية من جوجل تدعم أكثر من 100 لغة.',
   'https://translate.google.com', 'مجاني', 'Google', 7.5, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   'استخدم الآن');

-- Arabic-tools content
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO content (site_id, title, slug, body, excerpt, type, status, category_id, tags, author) VALUES
  ((SELECT id FROM arabic),
   'أفضل أدوات الترجمة العربية في 2026: مقارنة شاملة',
   'best-arabic-translation-tools-2026',
   '<h2>مقارنة أفضل أدوات الترجمة</h2><p>اختيار أداة الترجمة المناسبة أمر بالغ الأهمية للمحتوى العربي عالي الجودة.</p>',
   'قارن بين أفضل أدوات الترجمة العربية من حيث الدقة والسعر والميزات.',
   'comparison', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   ARRAY['ترجمة', 'مقارنة', 'أدوات'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'مراجعة Canva للتصميم العربي: هل تستحق الاشتراك؟',
   'canva-arabic-review',
   '<h2>مراجعة Canva</h2><p>Canva هي واحدة من أشهر منصات التصميم في العالم مع دعم ممتاز للخط العربي.</p>',
   'مراجعة شاملة لمنصة Canva ودعمها للتصميم باللغة العربية.',
   'review', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'design-tools'),
   ARRAY['تصميم', 'مراجعة', 'canva'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'دليل المبتدئين لتحسين SEO للمحتوى العربي',
   'beginners-guide-arabic-seo',
   '<h2>ما هو SEO؟</h2><p>تحسين محركات البحث (SEO) هو عملية تحسين موقعك ليظهر في نتائج البحث.</p>',
   'تعلم أساسيات تحسين محركات البحث للمحتوى العربي.',
   'guide', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'seo-tools'),
   ARRAY['seo', 'دليل', 'مبتدئين'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'كيف تختار أفضل أداة كتابة عربية في 2026',
   'how-to-choose-arabic-writing-tool',
   '<h2>اختيار أداة الكتابة المناسبة</h2><p>أداة الكتابة الجيدة تساعدك على إنتاج محتوى عربي احترافي بسرعة.</p>',
   'دليل شامل لاختيار أفضل أداة كتابة باللغة العربية.',
   'article', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'writing-tools'),
   ARRAY['كتابة', 'أدوات', 'دليل'], 'فريق Arabic Tools');

-- Arabic-tools content-products links
WITH
  tr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'best-arabic-translation-tools-2026'),
  cr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'canva-arabic-review'),
  sg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'beginners-guide-arabic-seo'),
  wg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'how-to-choose-arabic-writing-tool'),
  deepl    AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'deepl-translator'),
  gtrans   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'google-translate'),
  canva    AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'canva-arabic'),
  ahrefs   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'ahrefs'),
  grammarly AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'grammarly-arabic')
INSERT INTO content_products (content_id, product_id, role) VALUES
  ((SELECT id FROM tr), (SELECT id FROM deepl),    'hero'),
  ((SELECT id FROM tr), (SELECT id FROM gtrans),   'hero'),
  ((SELECT id FROM cr), (SELECT id FROM canva),    'hero'),
  ((SELECT id FROM sg), (SELECT id FROM ahrefs),   'hero'),
  ((SELECT id FROM wg), (SELECT id FROM grammarly), 'hero');

-- Crypto content-products links
WITH
  ea AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'best-crypto-exchanges-2026'),
  lr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'ledger-nano-x-review'),
  dg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'beginners-guide-to-defi'),
  wg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'how-to-choose-crypto-wallet'),
  binance  AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'binance'),
  coinbase AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'coinbase'),
  ledger   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'ledger-nano-x'),
  trezor   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'trezor-model-t'),
  aave     AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'aave'),
  kraken   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'kraken')
INSERT INTO content_products (content_id, product_id, role) VALUES
  ((SELECT id FROM ea), (SELECT id FROM binance),  'hero'),
  ((SELECT id FROM ea), (SELECT id FROM coinbase), 'hero'),
  ((SELECT id FROM ea), (SELECT id FROM kraken),   'hero'),
  ((SELECT id FROM lr), (SELECT id FROM ledger),   'hero'),
  ((SELECT id FROM lr), (SELECT id FROM trezor),   'hero'),
  ((SELECT id FROM dg), (SELECT id FROM aave),     'hero'),
  ((SELECT id FROM wg), (SELECT id FROM ledger),   'hero'),
  ((SELECT id FROM wg), (SELECT id FROM trezor),   'hero');

-- ═══════════════════════════════════════════════════════
-- TABLES ADDED IN LATER MIGRATIONS
-- (appended here to keep this snapshot current)
-- ═══════════════════════════════════════════════════════

-- ── audit_log (migration 00001) ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id    uuid REFERENCES sites(id) ON DELETE SET NULL,
  user_id    uuid REFERENCES admin_users(id) ON DELETE SET NULL,
  action     text NOT NULL,
  entity     text NOT NULL DEFAULT '',
  entity_id  text NOT NULL DEFAULT '',
  details    jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_site ON audit_log(site_id, created_at DESC);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_full_access_audit_log" ON audit_log
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── niche_templates (migration 00019) ───────────────────────────────
CREATE TABLE IF NOT EXISTS niche_templates (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name             text NOT NULL,
  slug             text NOT NULL UNIQUE,
  description      text DEFAULT '',
  default_theme    jsonb DEFAULT '{}'::jsonb,
  default_nav      jsonb DEFAULT '[]'::jsonb,
  default_footer   jsonb DEFAULT '[]'::jsonb,
  default_features jsonb DEFAULT '{}'::jsonb,
  monetization_type text DEFAULT 'affiliate',
  language         text DEFAULT 'en',
  direction        text DEFAULT 'ltr',
  custom_css       text DEFAULT '',
  social_links     jsonb DEFAULT '{}'::jsonb,
  is_builtin       boolean DEFAULT false,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

ALTER TABLE niche_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "niche_templates_service_all" ON niche_templates
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── web_vitals (migration 00023) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS web_vitals (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text NOT NULL,
  value      double precision NOT NULL,
  metric_id  text,
  page       text,
  href       text,
  rating     text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_web_vitals_name_created
  ON web_vitals (name, created_at DESC);

ALTER TABLE web_vitals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "web_vitals_anon_insert" ON web_vitals
  FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "web_vitals_service_all" ON web_vitals
  FOR ALL TO service_role USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── site_modules (migration 00028) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS site_modules (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id    uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  module_key text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  config     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (site_id, module_key)
);

CREATE INDEX IF NOT EXISTS idx_site_modules_site ON site_modules(site_id);

ALTER TABLE site_modules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "site_modules_public_read" ON site_modules FOR SELECT USING (true);
CREATE POLICY "site_modules_service_all" ON site_modules
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── site_feature_flags (migration 00028) ────────────────────────────
CREATE TABLE IF NOT EXISTS site_feature_flags (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  flag_key    text NOT NULL,
  is_enabled  boolean NOT NULL DEFAULT false,
  description text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (site_id, flag_key)
);

CREATE INDEX IF NOT EXISTS idx_site_feature_flags_site ON site_feature_flags(site_id);

ALTER TABLE site_feature_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "site_feature_flags_public_read" ON site_feature_flags FOR SELECT USING (true);
CREATE POLICY "site_feature_flags_service_all" ON site_feature_flags
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── roles (migration 00028) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roles (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL UNIQUE,
  label       text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_system   boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roles_public_read" ON roles FOR SELECT USING (true);
CREATE POLICY "roles_service_all" ON roles
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── permissions (migration 00028) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS permissions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  feature     text NOT NULL,
  action      text NOT NULL,
  description text NOT NULL DEFAULT '',
  UNIQUE (feature, action)
);

ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "permissions_public_read" ON permissions FOR SELECT USING (true);
CREATE POLICY "permissions_service_all" ON permissions
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── role_permissions (migration 00028) ──────────────────────────────
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id       uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "role_permissions_public_read" ON role_permissions FOR SELECT USING (true);
CREATE POLICY "role_permissions_service_all" ON role_permissions
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── user_site_roles (migration 00028) ───────────────────────────────
CREATE TABLE IF NOT EXISTS user_site_roles (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  site_id    uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  role_id    uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, site_id)
);

ALTER TABLE user_site_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_site_roles_service_all" ON user_site_roles
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── integration_providers (migration 00028) ─────────────────────────
CREATE TABLE IF NOT EXISTS integration_providers (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key           text NOT NULL UNIQUE,
  name          text NOT NULL,
  category      text NOT NULL,
  description   text NOT NULL DEFAULT '',
  config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_builtin    boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE integration_providers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "integration_providers_public_read" ON integration_providers FOR SELECT USING (true);
CREATE POLICY "integration_providers_service_all" ON integration_providers
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── site_integrations (migration 00028) ─────────────────────────────
CREATE TABLE IF NOT EXISTS site_integrations (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id      uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  provider_key text NOT NULL REFERENCES integration_providers(key) ON DELETE CASCADE,
  is_enabled   boolean NOT NULL DEFAULT false,
  config       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (site_id, provider_key)
);

ALTER TABLE site_integrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "site_integrations_service_all" ON site_integrations
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── ai_drafts (migration 00029) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_drafts (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id          uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  title            text NOT NULL,
  slug             text NOT NULL,
  body             text NOT NULL DEFAULT '',
  excerpt          text NOT NULL DEFAULT '',
  content_type     text NOT NULL DEFAULT 'article',
  topic            text NOT NULL DEFAULT '',
  keywords         text[] NOT NULL DEFAULT '{}',
  ai_provider      text NOT NULL DEFAULT '',
  status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'approved', 'rejected', 'published')),
  generated_at     timestamptz NOT NULL DEFAULT now(),
  reviewed_at      timestamptz,
  reviewed_by      text,
  meta_title       text,
  meta_description text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_drafts_site_status ON ai_drafts(site_id, status);
CREATE INDEX IF NOT EXISTS idx_ai_drafts_site_created ON ai_drafts(site_id, created_at DESC);

ALTER TABLE ai_drafts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ai_drafts_service_all" ON ai_drafts
  FOR ALL USING (true) WITH CHECK (true);

-- ── affiliate_networks (migration 00029) ────────────────────────────
CREATE TABLE IF NOT EXISTS affiliate_networks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id      uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  network      text NOT NULL CHECK (network IN ('cj', 'partnerstack', 'admitad', 'direct')),
  publisher_id text NOT NULL DEFAULT '',
  api_key_ref  text NOT NULL DEFAULT '',
  is_active    boolean NOT NULL DEFAULT true,
  config       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (site_id, network)
);

CREATE INDEX IF NOT EXISTS idx_affiliate_networks_site ON affiliate_networks(site_id);

ALTER TABLE affiliate_networks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "affiliate_networks_service_all" ON affiliate_networks
  FOR ALL USING (true) WITH CHECK (true);



-- ── public RLS hardening: products / content / pages require active site ──
-- (migration 00031 — replaces the simpler policies defined above)
-- Products
DROP POLICY IF EXISTS "public_read_active_products" ON products;
CREATE POLICY "public_read_active_products" ON products
  FOR SELECT USING (
    status = 'active'
    AND EXISTS (SELECT 1 FROM sites WHERE sites.id = products.site_id AND sites.is_active = true)
  );

-- Content
DROP POLICY IF EXISTS "public_read_published_content" ON content;
CREATE POLICY "public_read_published_content" ON content
  FOR SELECT USING (
    status = 'published'
    AND EXISTS (SELECT 1 FROM sites WHERE sites.id = content.site_id AND sites.is_active = true)
  );

-- Pages
DROP POLICY IF EXISTS "public_read_published_pages" ON pages;
CREATE POLICY "public_read_published_pages" ON pages
  FOR SELECT USING (
    is_published = true
    AND EXISTS (SELECT 1 FROM sites WHERE sites.id = pages.site_id AND sites.is_active = true)
  );

-- Content-products join
DROP POLICY IF EXISTS "public_read_content_products" ON content_products;
CREATE POLICY "public_read_content_products" ON content_products
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM content c WHERE c.id = content_products.content_id AND c.status = 'published')
    AND EXISTS (SELECT 1 FROM products p WHERE p.id = content_products.product_id AND p.status = 'active')
    AND EXISTS (
      SELECT 1 FROM sites s JOIN content c ON c.site_id = s.id
      WHERE c.id = content_products.content_id AND s.is_active = true
    )
  );
