-- Seed data is now in migrations/00003_seed_data.sql
-- This file is kept for compatibility with `supabase db reset`
-- which automatically runs seed.sql after all migrations.
--
-- Since seed data is already applied via migration 00003,
-- this file intentionally left minimal.
