// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import i18nextPlugin from "eslint-plugin-i18next";
import i18nDefaultOptions from "eslint-plugin-i18next/lib/options/defaults.js";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import storybook from "eslint-plugin-storybook";

const __dirname = dirname(fileURLToPath(import.meta.url));
const i18nBaseline = JSON.parse(
  readFileSync(join(__dirname, "i18n-literal-baseline.json"), "utf-8"),
);
const i18nLiteralRuleOptions = {
  mode: "jsx-text-only",
  words: {
    exclude: [...i18nDefaultOptions.words.exclude, ...i18nBaseline],
  },
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Open-Next build artifacts (generated; must not be linted)
    ".open-next/**",
    // Storybook static output (generated)
    "storybook-static/**",
  ]),
  ...storybook.configs["flat/recommended"],
  {
    plugins: {
      "react-hooks": reactHooksPlugin,
      i18next: i18nextPlugin,
    },
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/preserve-manual-memoization": "warn",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Accessibility rules (Audit L9-12, A68-F1: upgraded warn→error)
      // jsx-a11y plugin is already registered by eslint-config-next.
      // These MUST be "error" so CI fails on new a11y violations.
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-role": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/no-noninteractive-element-interactions": "error",
      "jsx-a11y/click-events-have-key-events": "error",
      "jsx-a11y/no-static-element-interactions": "error",
      "jsx-a11y/label-has-associated-control": "error",
      // Import ordering (Audit 5.2)
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          pathGroups: [{ pattern: "@/**", group: "internal", position: "after" }],
          "newlines-between": "never",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      // i18n hard requirement: new JSX literal strings must be translated.
      // Existing literals are grand-fathered by i18n-literal-baseline.json
      // (generated by scripts/generate-i18n-baseline.mjs) so lint passes today
      // while any new string fails CI. French, Arabic and Darija (ary) locales
      // are registered in src/lib/i18n.ts.
      "i18next/no-literal-string": ["error", i18nLiteralRuleOptions],
    },
  },
  {
    // S-17: Prevent scripts/** paths from being imported into Worker bundle.
    // Files under scripts/ are meant for local/CI use only and may contain
    // service-role keys or Node-only APIs that must never reach the browser.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/scripts/*", "**/scripts/**"],
              message:
                "S-17: scripts/** must not be imported from src/** — they are not part of the Worker bundle.",
            },
          ],
        },
      ],
    },
  },
  {
    // A87-F10: Prevent .skip from slipping into main on test files.
    // describe.skip / it.skip / test.skip silently disable coverage and let
    // regressions through (the skipped RLS suite is the canonical example).
    // Use describe.skipIf() with a documented env guard when genuinely needed.
    files: ["src/**/*.test.{ts,tsx}", "e2e/**/*.spec.ts"],
    rules: {
      // i18n ratchet applies to UI code, not test code.
      "i18next/no-literal-string": "off",
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.property.name='skip'][callee.object.name='describe']",
          message:
            "A87-F10: describe.skip is forbidden in CI. Use describe.skipIf(condition) with a documented env guard, or remove the skip.",
        },
        {
          selector: "CallExpression[callee.property.name='skip'][callee.object.name='it']",
          message:
            "A87-F10: it.skip is forbidden in CI. Use it.skipIf(condition) with a documented env guard, or remove the skip.",
        },
        {
          selector: "CallExpression[callee.property.name='skip'][callee.object.name='test']",
          message:
            "A87-F10: test.skip is forbidden in CI. Use test.skipIf(condition) with a documented env guard, or remove the skip.",
        },
        {
          selector:
            "CallExpression[callee.property.name='skipIf'][callee.object.name='describe'] > Literal[value=true]:first-child",
          message:
            "FR-35: describe.skipIf(true) permanently disables tests. Use an env-guard variable instead.",
        },
        {
          selector:
            "CallExpression[callee.property.name='skipIf'][callee.object.name='it'] > Literal[value=true]:first-child",
          message:
            "FR-35: it.skipIf(true) permanently disables tests. Use an env-guard variable instead.",
        },
        {
          selector:
            "CallExpression[callee.property.name='skipIf'][callee.object.name='test'] > Literal[value=true]:first-child",
          message:
            "FR-35: test.skipIf(true) permanently disables tests. Use an env-guard variable instead.",
        },
      ],
    },
  },

  // ENV-001 rule: enforce process.env access through src/lib/env.ts
  // Deferred: the rule is ready (see src/lib/env.ts for typed getters) but
  // activating it now would exceed the ESLint warning baseline (~245 new
  // warnings from ~230 remaining call sites). Enable in a dedicated cleanup
  // PR once the first-wave getters in env.ts have been rolled out more widely.
  // The getters added in this PR (getCronSecret, getPhiEncryptionKey, etc.)
  // are already in place and can be adopted incrementally.
]);

export default eslintConfig;
