import {
  Stethoscope,
  Heart,
  Scan,
  Baby,
  HeartHandshake,
  Eye,
  Ear,
  Brain,
  BrainCircuit,
  Bone,
  Activity,
  Apple,
  Wind,
  Droplets,
  Accessibility,
  Dumbbell,
  MessageCircle,
  Salad,
  HeartPulse,
  Syringe,
  Glasses,
  Footprints,
  PersonStanding,
  ScanLine,
  TestTube,
  MonitorCheck,
  Microscope,
  Pill,
  ShoppingBag,
  Wrench,
  Cog,
  Smile,
  Building2,
  Hospital,
  Droplet,
  StretchVertical,
  Sparkles,
  FlaskConical,
} from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  Stethoscope,
  Heart,
  Scan,
  Baby,
  HeartHandshake,
  Eye,
  Ear,
  Brain,
  BrainCircuit,
  Bone,
  Activity,
  Apple,
  Wind,
  Droplets,
  Accessibility,
  Dumbbell,
  MessageCircle,
  Salad,
  HeartPulse,
  Syringe,
  Glasses,
  Footprints,
  PersonStanding,
  ScanLine,
  TestTube,
  MonitorCheck,
  Microscope,
  Pill,
  ShoppingBag,
  Wrench,
  Cog,
  Smile,
  Building2,
  Hospital,
  Droplet,
  StretchVertical,
  Sparkles,
  FlaskConical,
};

interface ClinicTypeIconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
}

export function ClinicTypeIcon({ name, ...props }: ClinicTypeIconProps) {
  const Icon = ICON_MAP[name] ?? Stethoscope;
  return <Icon {...props} />;
}
