"use client";

/**
 * QR Code Generator Component
 *
 * Generates a scannable QR code SVG for the patient portal URL.
 * Uses the 'qrcode' library for standards-compliant QR code generation.
 * Can be printed or downloaded as SVG/PNG.
 */

import { useState, useMemo, useCallback, useRef } from "react";
import { logger } from "@/lib/logger";
import { Download, Printer, Copy, Check, QrCode } from "lucide-react";
import QRCodeLib from "qrcode";
import { escapeHtml } from "@/lib/escape-html";

interface QrCodeGeneratorProps {
  url: string;
  title?: string;
  subtitle?: string;
  size?: number;
  className?: string;
}

// ---- Component ----

export function QrCodeGenerator({
  url,
  title = "Patient Portal",
  subtitle,
  size = 200,
  className,
}: QrCodeGeneratorProps) {
  const [copied, setCopied] = useState(false);
  const svgContainerRef = useRef<HTMLDivElement>(null);

  const svgContent = useMemo(() => {
    // Generate a standards-compliant, scannable QR code as SVG string.
    let svg = "";
    QRCodeLib.toString(url, {
      type: "svg",
      width: size,
      margin: 1,
      errorCorrectionLevel: "M",
    }, (err: Error | null | undefined, svgStr: string) => {
      if (!err) svg = svgStr;
    });
    return svg;
  }, [url, size]);

  const copyUrl = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      logger.warn("Clipboard write failed", { context: "qr-code-generator", error: err });
    }
  }, [url]);

  const downloadSvg = useCallback(() => {
    const blob = new Blob([svgContent], { type: "image/svg+xml" });
    const downloadUrl = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = downloadUrl;
    link.download = "patient-portal-qr.svg";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(downloadUrl);
  }, [svgContent]);

  const printQr = useCallback(() => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${escapeHtml(title)} QR Code</title>
        <style>
          body { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; font-family: system-ui, sans-serif; }
          .title { font-size: 24px; font-weight: bold; margin-bottom: 8px; }
          .subtitle { font-size: 14px; color: #666; margin-bottom: 24px; }
          .url { font-size: 12px; color: #999; margin-top: 16px; word-break: break-all; max-width: 300px; text-align: center; }
        </style>
      </head>
      <body>
        <div class="title">${escapeHtml(title)}</div>
        ${subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : ""}
        ${svgContent}
        <div class="url">${escapeHtml(url)}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.onload = () => printWindow.print();
  }, [svgContent, title, subtitle, url]);

  return (
    <div
      className={`rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-6 ${className ?? ""}`}
    >
      <div className="flex items-center gap-2 mb-4">
        <QrCode className="h-5 w-5 text-blue-500" />
        <h3 className="text-lg font-semibold">{title}</h3>
      </div>

      {subtitle && (
        <p className="text-sm text-gray-500 mb-4">{subtitle}</p>
      )}

      {/* QR Code */}
      <div
        ref={svgContainerRef}
        className="flex justify-center p-4 bg-white rounded-lg mb-4"
        // SAFETY: svgContent is generated by the 'qrcode' library —
        // only produces SVG elements with numeric coordinates.
        // No user-controlled HTML is injected.
        dangerouslySetInnerHTML={{ __html: svgContent }}
      />

      {/* URL */}
      <div className="flex items-center gap-2 mb-4">
        <input
          value={url}
          readOnly
          className="flex-1 px-3 py-2 text-sm border rounded-lg bg-gray-50 dark:bg-gray-800 truncate"
        />
        <button
          onClick={copyUrl}
          className="p-2 border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
          title="Copy URL"
        >
          {copied ? (
            <Check className="h-4 w-4 text-green-500" />
          ) : (
            <Copy className="h-4 w-4" />
          )}
        </button>
      </div>

      {/* Actions */}
      <div className="flex gap-2">
        <button
          onClick={downloadSvg}
          className="flex-1 flex items-center justify-center gap-2 py-2 px-3 text-sm border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        >
          <Download className="h-4 w-4" />
          Download SVG
        </button>
        <button
          onClick={printQr}
          className="flex-1 flex items-center justify-center gap-2 py-2 px-3 text-sm border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        >
          <Printer className="h-4 w-4" />
          Print
        </button>
      </div>
    </div>
  );
}
