/**
 * Demo / seed data for the notification system.
 *
 * Extracted from notifications.ts so that production bundles stay lean
 * and test files can import fixtures without pulling in the full engine.
 */

import type { NotificationLogEntry, InAppNotification } from "@/lib/notifications";

export const demoNotificationLog: NotificationLogEntry[] = [
  {
    id: "nl1",
    trigger: "booking_confirmation",
    channel: "whatsapp",
    recipientId: "p1",
    recipientName: "Karim Mansouri",
    recipientRole: "patient",
    title: "Appointment Confirmed",
    body: "Hello Karim Mansouri, your appointment with Dr. Ahmed Benali is confirmed for 2026-03-19 at 09:00. Reply CANCEL to cancel. Demo Clinic",
    status: "delivered",
    priority: "high",
    createdAt: "2026-03-18T14:30:00Z",
    sentAt: "2026-03-18T14:30:01Z",
  },
  {
    id: "nl2",
    trigger: "reminder_24h",
    channel: "whatsapp",
    recipientId: "p1",
    recipientName: "Karim Mansouri",
    recipientRole: "patient",
    title: "Appointment Tomorrow",
    body: "Reminder: You have an appointment with Dr. Ahmed Benali tomorrow at 09:00. Demo Clinic",
    status: "delivered",
    priority: "high",
    createdAt: "2026-03-18T09:00:00Z",
    sentAt: "2026-03-18T09:00:02Z",
  },
  {
    id: "nl3",
    trigger: "reminder_2h",
    channel: "whatsapp",
    recipientId: "p1",
    recipientName: "Karim Mansouri",
    recipientRole: "patient",
    title: "Appointment in 2 Hours",
    body: "Your appointment with Dr. Ahmed Benali is in 2 hours at 09:00. Please arrive 10 minutes early. Demo Clinic",
    status: "delivered",
    priority: "urgent",
    createdAt: "2026-03-19T07:00:00Z",
    sentAt: "2026-03-19T07:00:01Z",
  },
  {
    id: "nl4",
    trigger: "new_booking",
    channel: "in_app",
    recipientId: "d1",
    recipientName: "Dr. Ahmed Benali",
    recipientRole: "doctor",
    title: "New Appointment Booked",
    body: "A new appointment has been booked for Nadia El Fassi with Dr. Ahmed Benali on 2026-03-19 at 09:30 for Follow-up Visit.",
    status: "read",
    priority: "normal",
    createdAt: "2026-03-17T16:00:00Z",
    sentAt: "2026-03-17T16:00:00Z",
    readAt: "2026-03-17T16:05:00Z",
  },
  {
    id: "nl5",
    trigger: "payment_received",
    channel: "whatsapp",
    recipientId: "p1",
    recipientName: "Karim Mansouri",
    recipientRole: "patient",
    title: "Payment Confirmed",
    body: "Hello Karim Mansouri, we received your payment of 200 MAD via insurance. Invoice: inv1. Thank you! — Demo Clinic",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-19T09:45:00Z",
    sentAt: "2026-03-19T09:45:01Z",
  },
  {
    id: "nl6",
    trigger: "cancellation",
    channel: "whatsapp",
    recipientId: "p6",
    recipientName: "Amina Chaoui",
    recipientRole: "patient",
    title: "Appointment Cancelled",
    body: "Your appointment with Dr. Ahmed Benali on 2026-03-20 at 11:30 has been cancelled. Contact us to reschedule.",
    status: "delivered",
    priority: "high",
    createdAt: "2026-03-19T15:00:00Z",
    sentAt: "2026-03-19T15:00:02Z",
  },
  {
    id: "nl7",
    trigger: "new_patient_registered",
    channel: "in_app",
    recipientId: "admin1",
    recipientName: "Clinic Admin",
    recipientRole: "clinic_admin",
    title: "New Patient Registration",
    body: "A new patient has registered: Amina Chaoui.",
    status: "sent",
    priority: "low",
    createdAt: "2026-03-19T10:00:00Z",
    sentAt: "2026-03-19T10:00:00Z",
  },
  {
    id: "nl8",
    trigger: "prescription_ready",
    channel: "whatsapp",
    recipientId: "p3",
    recipientName: "Omar Tazi",
    recipientRole: "patient",
    title: "Prescription Ready",
    body: "Hello Omar Tazi, your prescription from Dr. Youssef El Amrani is ready for pickup at Demo Clinic.",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-19T11:30:00Z",
    sentAt: "2026-03-19T11:30:01Z",
  },
  {
    id: "nl9",
    trigger: "no_show",
    channel: "whatsapp",
    recipientId: "p5",
    recipientName: "Hassan Idrissi",
    recipientRole: "patient",
    title: "Missed Appointment",
    body: "Hello Hassan Idrissi, we noticed you missed your appointment on 2026-03-18. Would you like to reschedule?",
    status: "failed",
    priority: "normal",
    createdAt: "2026-03-18T18:00:00Z",
    sentAt: "2026-03-18T18:00:05Z",
    error: "WhatsApp number not verified",
  },
  {
    id: "nl10",
    trigger: "new_review",
    channel: "in_app",
    recipientId: "d1",
    recipientName: "Dr. Ahmed Benali",
    recipientRole: "doctor",
    title: "New Patient Review",
    body: "Karim M. left a 5-star review: \"Excellent doctor, very professional and caring.\"",
    status: "read",
    priority: "low",
    createdAt: "2026-03-15T12:00:00Z",
    sentAt: "2026-03-15T12:00:00Z",
    readAt: "2026-03-15T14:00:00Z",
  },
  {
    id: "nl11",
    trigger: "booking_confirmation",
    channel: "in_app",
    recipientId: "p2",
    recipientName: "Nadia El Fassi",
    recipientRole: "patient",
    title: "Appointment Confirmed",
    body: "Your appointment with Dr. Ahmed Benali is confirmed for 2026-03-19 at 09:30. Service: Follow-up Visit. Demo Clinic",
    status: "read",
    priority: "high",
    createdAt: "2026-03-17T16:00:00Z",
    sentAt: "2026-03-17T16:00:00Z",
    readAt: "2026-03-17T18:00:00Z",
  },
  {
    id: "nl12",
    trigger: "reminder_24h",
    channel: "in_app",
    recipientId: "p3",
    recipientName: "Omar Tazi",
    recipientRole: "patient",
    title: "Appointment Tomorrow",
    body: "Reminder: You have an appointment with Dr. Youssef El Amrani tomorrow at 14:00. Demo Clinic",
    status: "sent",
    priority: "high",
    createdAt: "2026-03-19T14:00:00Z",
    sentAt: "2026-03-19T14:00:00Z",
  },
];

export const demoInAppNotifications: InAppNotification[] = [
  {
    id: "ian1",
    userId: "p1",
    trigger: "booking_confirmation",
    title: "Appointment Confirmed",
    message: "Your appointment with Dr. Ahmed Benali is confirmed for March 20 at 09:00.",
    channel: "in_app",
    status: "delivered",
    priority: "high",
    createdAt: "2026-03-19T14:30:00Z",
  },
  {
    id: "ian2",
    userId: "p1",
    trigger: "reminder_24h",
    title: "Appointment Tomorrow",
    message: "Reminder: You have an appointment with Dr. Ahmed Benali tomorrow at 09:00.",
    channel: "in_app",
    status: "delivered",
    priority: "high",
    createdAt: "2026-03-19T09:00:00Z",
  },
  {
    id: "ian3",
    userId: "p1",
    trigger: "payment_received",
    title: "Payment Confirmed",
    message: "Payment of 200 MAD received via insurance for your visit on March 19. Thank you!",
    channel: "in_app",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-19T09:45:00Z",
  },
  {
    id: "ian4",
    userId: "p1",
    trigger: "prescription_ready",
    title: "Prescription Ready",
    message: "Your prescription from Dr. Ahmed Benali is ready. You can view it in your patient portal.",
    channel: "in_app",
    status: "read",
    priority: "normal",
    createdAt: "2026-03-18T11:00:00Z",
    readAt: "2026-03-18T12:00:00Z",
  },
  {
    id: "ian5",
    userId: "d1",
    trigger: "new_booking",
    title: "New Appointment Booked",
    message: "A new appointment has been booked for Omar Tazi on March 20 at 14:00 for Follow-up Visit.",
    channel: "in_app",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-18T16:00:00Z",
  },
  {
    id: "ian6",
    userId: "d1",
    trigger: "new_review",
    title: "New Patient Review",
    message: "Karim M. left a 5-star review: \"Excellent doctor, very professional and caring.\"",
    channel: "in_app",
    status: "read",
    priority: "low",
    createdAt: "2026-03-15T12:00:00Z",
    readAt: "2026-03-15T14:00:00Z",
  },
  {
    id: "ian7",
    userId: "admin1",
    trigger: "new_patient_registered",
    title: "New Patient Registration",
    message: "A new patient has registered: Amina Chaoui. Phone: +212 6 66 77 88 99.",
    channel: "in_app",
    status: "delivered",
    priority: "low",
    createdAt: "2026-03-19T10:00:00Z",
  },
  {
    id: "ian8",
    userId: "admin1",
    trigger: "new_booking",
    title: "New Appointment Booked",
    message: "Salma Berrada booked a Pediatric Consultation with Dr. Fatima Zahra on March 19 at 10:30.",
    channel: "in_app",
    status: "read",
    priority: "normal",
    createdAt: "2026-03-17T14:00:00Z",
    readAt: "2026-03-17T15:00:00Z",
  },
  {
    id: "ian9",
    userId: "admin1",
    trigger: "payment_received",
    title: "Payment Received",
    message: "Payment of 200 MAD received from Karim Mansouri via insurance.",
    channel: "in_app",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-19T09:45:00Z",
  },
  {
    id: "ian10",
    userId: "admin1",
    trigger: "no_show",
    title: "Patient No-Show",
    message: "Hassan Idrissi did not show up for their appointment with Dr. Youssef El Amrani on March 18.",
    channel: "in_app",
    status: "delivered",
    priority: "normal",
    createdAt: "2026-03-18T18:00:00Z",
  },
];
