#!/usr/bin/env bash
# scripts/check-schema-drift.sh
#
# Regenerates supabase/schema.sql and types/supabase.ts from the live
# linked Supabase project and exits non-zero if they differ from what is
# checked in.
#
# Usage (local):
#   ./scripts/check-schema-drift.sh
#
# Usage (CI — add as a job step after migrations are applied):
#   - name: Check schema/types drift
#     run: bash scripts/check-schema-drift.sh
#
# Prerequisites:
#   supabase CLI installed and logged in (`supabase login`)
#   Project linked (`supabase link --project-ref <ref>`)
#
# Source-of-truth reminder:
#   - types/supabase.ts   → GENERATED by `supabase gen types typescript`.
#                           Holds the `Database` type used by
#                           createClient<Database>() in lib/supabase.ts
#                           and lib/supabase-server.ts.
#   - types/database.ts   → HAND-CURATED app-level row types
#                           (NewsletterSubscriberRow, ProductRow, …).
#                           NOT regenerated here.
set -euo pipefail

echo "▶ Dumping live schema..."
supabase db dump --linked > supabase/schema.sql

echo "▶ Regenerating TypeScript types..."
supabase gen types typescript --linked > types/supabase.ts

echo "▶ Checking for drift..."
if ! git diff --exit-code supabase/schema.sql types/supabase.ts; then
  echo ""
  echo "❌ Schema drift detected."
  echo "   supabase/schema.sql or types/supabase.ts are out of sync with the live DB."
  echo "   Run this script locally, review the diff, commit the regenerated files, and re-run CI."
  exit 1
fi

echo "✅ No drift — schema.sql and supabase.ts match the live DB."
