#!/usr/bin/env bash
#
# dev-bootstrap.sh — one command to stand up the LOCAL development environment.
#
# What it does:
#   1. Checks prerequisites (Node >= 22.13, Docker, Supabase CLI).
#   2. Installs npm dependencies.
#   3. Starts the local Supabase stack (runs migrations + seed.sql -> demo clinic).
#   4. Writes .env.local with the local Supabase URL + anon key (auto-detected).
#   5. Prints the next step (`npm run dev`).
#
# It is idempotent and safe to re-run. An existing .env.local is backed up,
# never overwritten silently.
#
# Usage:
#   bash scripts/dev-bootstrap.sh
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# ---- pretty output helpers -------------------------------------------------
info() { printf '\033[1;34m▸ %s\033[0m\n' "$*"; }
ok() { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*"; }
fail() {
  printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2
  exit 1
}

# ---- 1. prerequisites ------------------------------------------------------
info "Checking prerequisites…"

command -v node >/dev/null 2>&1 || fail "Node.js is not installed. Install Node 22.13+ from https://nodejs.org"

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
NODE_MINOR="$(node -p 'process.versions.node.split(".")[1]')"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 13 ]; }; then
  fail "Node $(node -v) is too old. This project requires Node >= 22.13."
fi
ok "Node $(node -v)"

command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Local Supabase needs Docker: https://www.docker.com/products/docker-desktop/"
docker info >/dev/null 2>&1 || fail "Docker is installed but not running. Start Docker Desktop and re-run."
ok "Docker is running"

# Supabase CLI may be a standalone binary or available via npx.
SUPABASE_CMD=""
if command -v supabase >/dev/null 2>&1; then
  SUPABASE_CMD="supabase"
elif npx --no-install supabase --version >/dev/null 2>&1; then
  SUPABASE_CMD="npx --no-install supabase"
else
  fail "Supabase CLI not found. Install it: https://supabase.com/docs/guides/local-development (e.g. 'brew install supabase/tap/supabase' or 'npm i -g supabase')."
fi
ok "Supabase CLI: $($SUPABASE_CMD --version 2>/dev/null | head -1)"

# ---- 2. install dependencies ----------------------------------------------
info "Installing npm dependencies (this can take a minute)…"
# Use `npm ci` only: it installs strictly from the integrity-hashed
# package-lock.json (a pinned, reproducible install). We deliberately do NOT
# fall back to `npm install`, which resolves versions at runtime (unpinned) —
# Scorecard Pinned-Dependencies flags that, and this repo always commits a
# lockfile, so the fallback would never be the intended path anyway.
if [ ! -f package-lock.json ]; then
  fail "package-lock.json not found. Run this from a clean clone of the repo (the lockfile is committed)."
fi
npm ci
ok "Dependencies installed"

# ---- 3. start local Supabase ----------------------------------------------
info "Starting local Supabase (Docker)… migrations + seed.sql will run."
# `supabase start` is a no-op if already running, so this is safe to re-run.
$SUPABASE_CMD start
ok "Local Supabase is up"

# ---- 4. write .env.local ---------------------------------------------------
info "Detecting local Supabase credentials…"
STATUS_ENV="$($SUPABASE_CMD status -o env 2>/dev/null || true)"

extract() {
  # extract VALUE for KEY from `supabase status -o env` output, stripping quotes
  printf '%s\n' "$STATUS_ENV" | grep -E "^$1=" | head -1 | sed -E "s/^$1=//; s/^\"//; s/\"$//"
}

LOCAL_API_URL="$(extract API_URL)"
LOCAL_ANON_KEY="$(extract ANON_KEY)"
LOCAL_SERVICE_KEY="$(extract SERVICE_ROLE_KEY)"

# Fallbacks to the well-known local defaults if parsing failed.
LOCAL_API_URL="${LOCAL_API_URL:-http://127.0.0.1:54321}"

if [ -z "$LOCAL_ANON_KEY" ]; then
  warn "Could not auto-detect the local anon key from 'supabase status -o env'."
  warn "Run '$SUPABASE_CMD status' and copy the 'anon key' into .env.local manually."
fi

ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ]; then
  BACKUP="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  warn "Existing $ENV_FILE backed up to $BACKUP"
fi

cat >"$ENV_FILE" <<EOF
# ---------------------------------------------------------------------------
# LOCAL DEVELOPMENT ENV — generated by scripts/dev-bootstrap.sh
# This file is git-ignored. Do NOT put production secrets here.
# Regenerate any time by re-running: bash scripts/dev-bootstrap.sh
# ---------------------------------------------------------------------------

# Local Supabase (from 'supabase start')
NEXT_PUBLIC_SUPABASE_URL=$LOCAL_API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$LOCAL_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$LOCAL_SERVICE_KEY

# Local site URL (subdomains work via *.localhost automatically)
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# Dev-only secrets (random, fine to regenerate). Not required to boot, but
# enable booking + cron locally without warnings.
BOOKING_TOKEN_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "dev-booking-secret-change-me")
CRON_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "dev-cron-secret-change-me")
EOF

ok "Wrote $ENV_FILE"

# ---- 5. done ---------------------------------------------------------------
echo
ok "Local dev environment is ready."
echo
echo "Next steps:"
echo "  1. Start the app:   npm run dev"
echo "  2. Open:            http://localhost:3000"
echo "  3. Demo clinic:     http://demo.localhost:3000"
echo
echo "Useful commands:"
echo "  $SUPABASE_CMD status      # show local URLs + keys (incl. Studio)"
echo "  $SUPABASE_CMD db reset    # wipe + re-apply migrations and seed.sql"
echo "  $SUPABASE_CMD stop        # shut the local stack down"
echo
echo "See docs/ENVIRONMENTS.md for the full dev/staging/production guide."
