/**
 * A199 / EU AI Act Art. 13-14: Every AI-powered clinical output must include
 * a disclaimer that the result is machine-generated and requires physician review.
 *
 * This constant is shared across all AI endpoints to ensure consistent
 * regulatory wording. Any updates to the text propagate to all routes.
 */
export const AI_CDS_DISCLAIMER =
  "Ce résultat est généré par un système d'aide à la décision clinique basé sur l'IA. " +
  "Il ne constitue pas un avis médical et doit être vérifié par un professionnel de santé qualifié " +
  "avant toute décision clinique. / " +
  "This output is generated by an AI-based clinical decision support system. " +
  "It does not constitute medical advice and must be reviewed by a qualified healthcare professional " +
  "before any clinical decision.";
