-- Stub migration: retained for Supabase migration-history compatibility.
--
-- This migration previously seeded the demo tenant ("Cabinet Demo Oltigo",
-- clinic c0000000-de00-0000-0000-000000000001) — a fake clinic plus fake
-- doctors, patients, services, time slots, appointments, reviews and
-- payments. Because it ran from supabase/migrations/, the demo tenant was
-- written to EVERY environment, including production ("Demo tenant lives in
-- production DB", per the original header).
--
-- The demo tenant is now seeded from supabase/seed.sql, which runs only on
-- local/CI (`supabase db reset` / `supabase start`) and NEVER in production
-- (production migrates via `supabase db push --include-all`, which does not
-- run seed.sql). Migration 00188 removes the demo rows this migration had
-- already written to the production database.
--
-- This file is reduced to a no-op stub so fresh databases never seed the
-- demo tenant via migrations, while the remote Supabase project still
-- records this version as applied (keeping local and remote migration lists
-- in sync). See migration 00003 for the same established pattern.

-- intentionally empty (no-op)
