-- Stub migration: retained for Supabase migration-history compatibility.
--
-- This migration previously enriched the demo tenant with prescriptions and
-- consultation notes (clinical sample content) and set the demo clinic's
-- `subdomain` column. Like 00046, it seeded fake data into every environment
-- including production.
--
-- The demo tenant (including this enrichment) is now seeded from
-- supabase/seed.sql, which runs only on local/CI and never in production.
-- Migration 00188 removes the demo rows already written to production.
--
-- Reduced to a no-op stub for the same reasons as the 00046 stub: stop
-- seeding demo data from migrations on fresh databases while keeping the
-- remote migration history in sync. See migration 00003 for the pattern.

-- intentionally empty (no-op)
