-- AI Team Dashboard: tables for AI agent tasks, alerts, and conversation logs

-- ── AI Agent Tasks ──────────────────────────────────────────────────────
-- Stores tasks/suggestions generated by AI agents (marketing, support, reminder).

CREATE TABLE IF NOT EXISTS ai_agent_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  agent_type text NOT NULL CHECK (agent_type IN ('marketing', 'support', 'reminder')),
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'dismissed')),
  category text,
  metadata jsonb DEFAULT '{}'::jsonb,
  due_date timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_tasks_clinic_id
  ON ai_agent_tasks(clinic_id);

CREATE INDEX IF NOT EXISTS idx_ai_agent_tasks_clinic_agent
  ON ai_agent_tasks(clinic_id, agent_type);

CREATE INDEX IF NOT EXISTS idx_ai_agent_tasks_clinic_status
  ON ai_agent_tasks(clinic_id, status);

ALTER TABLE ai_agent_tasks ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ai_agent_tasks'
      AND policyname = 'ai_agent_tasks_clinic_isolation'
  ) THEN
    CREATE POLICY ai_agent_tasks_clinic_isolation
      ON ai_agent_tasks
      FOR ALL
      USING (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      )
      WITH CHECK (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      );
  END IF;
END
$$;

-- ── AI Agent Alerts ─────────────────────────────────────────────────────
-- Stores alerts/notifications generated by AI agents.

CREATE TABLE IF NOT EXISTS ai_agent_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  agent_type text NOT NULL CHECK (agent_type IN ('marketing', 'support', 'reminder')),
  title text NOT NULL,
  message text NOT NULL,
  severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  is_read boolean NOT NULL DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_alerts_clinic_id
  ON ai_agent_alerts(clinic_id);

CREATE INDEX IF NOT EXISTS idx_ai_agent_alerts_clinic_unread
  ON ai_agent_alerts(clinic_id, is_read) WHERE is_read = false;

ALTER TABLE ai_agent_alerts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ai_agent_alerts'
      AND policyname = 'ai_agent_alerts_clinic_isolation'
  ) THEN
    CREATE POLICY ai_agent_alerts_clinic_isolation
      ON ai_agent_alerts
      FOR ALL
      USING (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      )
      WITH CHECK (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      );
  END IF;
END
$$;

-- ── AI Agent Conversations ──────────────────────────────────────────────
-- Stores chat conversations with individual AI agents.

CREATE TABLE IF NOT EXISTS ai_agent_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  agent_type text NOT NULL CHECK (agent_type IN ('marketing', 'support', 'reminder')),
  user_id uuid NOT NULL,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_clinic_id
  ON ai_agent_conversations(clinic_id);

CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_clinic_agent
  ON ai_agent_conversations(clinic_id, agent_type, user_id);

ALTER TABLE ai_agent_conversations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ai_agent_conversations'
      AND policyname = 'ai_agent_conversations_clinic_isolation'
  ) THEN
    CREATE POLICY ai_agent_conversations_clinic_isolation
      ON ai_agent_conversations
      FOR ALL
      USING (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      )
      WITH CHECK (
        clinic_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'clinic_id')::uuid
      );
  END IF;
END
$$;
