-- Compliance + uptime monitoring foundation.
-- Adds Moroccan Law 09-08 operational tables and internal uptime event storage.

CREATE TABLE IF NOT EXISTS public.compliance_cndp (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_number text UNIQUE,
  authorization_type text NOT NULL DEFAULT 'prior_authorization',
  authorization_number text,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'submitted', 'approved', 'rejected', 'renewal_required')),
  submitted_at timestamptz,
  approved_at timestamptz,
  expires_at timestamptz,
  renewal_due_at timestamptz,
  notes text,
  documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dsar_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dsar_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  requester_type text NOT NULL CHECK (requester_type IN ('patient', 'clinic_staff', 'external')),
  requester_name text NOT NULL,
  requester_email text NOT NULL,
  requester_phone text,
  clinic_id uuid REFERENCES public.clinics(id) ON DELETE SET NULL,
  request_type text NOT NULL CHECK (request_type IN ('access', 'rectification', 'deletion', 'portability', 'objection')),
  description text NOT NULL,
  status text NOT NULL DEFAULT 'received'
    CHECK (status IN ('received', 'in_progress', 'completed', 'rejected', 'extended')),
  legal_basis text,
  assigned_to uuid REFERENCES public.users(id) ON DELETE SET NULL,
  response_due_at timestamptz NOT NULL,
  responded_at timestamptz,
  response_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.data_breach_incidents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  detected_at timestamptz NOT NULL,
  -- Cannot use `GENERATED ALWAYS AS (detected_at + interval '72 hours') STORED`
  -- here: Postgres marks `timestamptz + interval` as STABLE (not IMMUTABLE) and
  -- rejects it for generated columns with SQLSTATE 42P17. The value is
  -- maintained by `trg_data_breach_cndp_due` below instead.
  cndp_notification_due_at timestamptz,
  cndp_notified_at timestamptz,
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  description text NOT NULL,
  affected_records_count integer,
  data_types_affected text[] NOT NULL DEFAULT '{}',
  clinics_affected uuid[] NOT NULL DEFAULT '{}',
  root_cause text,
  remediation_steps text,
  status text NOT NULL DEFAULT 'investigating'
    CHECK (status IN ('investigating', 'contained', 'notifying_cndp', 'cndp_notified', 'resolved')),
  created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.consent_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  clinic_id uuid REFERENCES public.clinics(id) ON DELETE SET NULL,
  consent_type text NOT NULL CHECK (consent_type IN (
    'terms_of_service',
    'privacy_policy',
    'health_data_processing',
    'marketing_communications',
    'whatsapp_notifications',
    'data_sharing_with_clinic'
  )),
  granted boolean NOT NULL,
  version text NOT NULL,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.data_retention_schedule (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data_type text UNIQUE NOT NULL,
  retention_days integer NOT NULL,
  legal_basis text NOT NULL,
  last_purge_at timestamptz,
  next_purge_at timestamptz,
  records_purged_last_run integer NOT NULL DEFAULT 0
);

INSERT INTO public.data_retention_schedule (data_type, retention_days, legal_basis)
VALUES
  ('patient_records', 3650, 'Medical records: 10 years'),
  ('appointment_logs', 1825, 'Business records: 5 years'),
  ('payment_records', 2555, 'Financial records: 7 years'),
  ('audit_logs', 1825, 'Compliance: 5 years minimum'),
  ('notification_logs', 90, 'Operational: 90 days'),
  ('support_ticket_messages', 1825, 'Support traceability: 5 years')
ON CONFLICT (data_type) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.uptime_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  monitor_name text NOT NULL,
  monitor_url text,
  event_type text NOT NULL CHECK (event_type IN ('down', 'up', 'degraded')),
  message text,
  response_time_ms integer,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_uptime_events_occurred_at
  ON public.uptime_events(occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_uptime_events_monitor_name
  ON public.uptime_events(monitor_name, occurred_at DESC);

CREATE OR REPLACE VIEW public.uptime_sla_monthly AS
SELECT
  monitor_name,
  date_trunc('month', occurred_at)::date AS month,
  count(*) FILTER (WHERE event_type = 'down') AS downtime_events,
  count(*) FILTER (WHERE event_type = 'up') AS recovery_events,
  ROUND(
    (
      1 - (
        (count(*) FILTER (WHERE event_type = 'down'))::numeric * 60
      ) / NULLIF(
        extract(
          epoch FROM (
            (date_trunc('month', occurred_at) + interval '1 month')
            - date_trunc('month', occurred_at)
          )
        ),
        0
      )
    ) * 100,
    3
  ) AS uptime_pct
FROM public.uptime_events
GROUP BY monitor_name, date_trunc('month', occurred_at)::date;

ALTER TABLE public.compliance_cndp ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dsar_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_breach_incidents ENABLE ROW LEVEL SECURITY;

-- Maintain cndp_notification_due_at = detected_at + 72h. Implemented as a
-- trigger because Postgres rejects this expression in a STORED GENERATED
-- column (timestamptz_pl_interval is STABLE, not IMMUTABLE).
CREATE OR REPLACE FUNCTION public.set_data_breach_cndp_due()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.cndp_notification_due_at := NEW.detected_at + interval '72 hours';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_data_breach_cndp_due ON public.data_breach_incidents;
CREATE TRIGGER trg_data_breach_cndp_due
BEFORE INSERT OR UPDATE OF detected_at ON public.data_breach_incidents
FOR EACH ROW EXECUTE FUNCTION public.set_data_breach_cndp_due();
ALTER TABLE public.consent_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_retention_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uptime_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'compliance_cndp' AND policyname = 'super_admin_compliance_cndp_all'
  ) THEN
    CREATE POLICY super_admin_compliance_cndp_all
      ON public.compliance_cndp
      FOR ALL
      TO authenticated
      USING (is_super_admin())
      WITH CHECK (is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'dsar_requests' AND policyname = 'super_admin_dsar_all'
  ) THEN
    CREATE POLICY super_admin_dsar_all
      ON public.dsar_requests
      FOR ALL
      TO authenticated
      USING (is_super_admin())
      WITH CHECK (is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'data_breach_incidents' AND policyname = 'super_admin_breach_all'
  ) THEN
    CREATE POLICY super_admin_breach_all
      ON public.data_breach_incidents
      FOR ALL
      TO authenticated
      USING (is_super_admin())
      WITH CHECK (is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'data_retention_schedule' AND policyname = 'super_admin_retention_all'
  ) THEN
    CREATE POLICY super_admin_retention_all
      ON public.data_retention_schedule
      FOR ALL
      TO authenticated
      USING (is_super_admin())
      WITH CHECK (is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'consent_records' AND policyname = 'user_own_or_super_admin_consent_read'
  ) THEN
    CREATE POLICY user_own_or_super_admin_consent_read
      ON public.consent_records
      FOR SELECT
      TO authenticated
      USING (user_id = auth.uid() OR is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'consent_records' AND policyname = 'service_role_insert_consent_records'
  ) THEN
    CREATE POLICY service_role_insert_consent_records
      ON public.consent_records
      FOR INSERT
      TO service_role
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'uptime_events' AND policyname = 'super_admin_uptime_all'
  ) THEN
    CREATE POLICY super_admin_uptime_all
      ON public.uptime_events
      FOR ALL
      TO authenticated
      USING (is_super_admin())
      WITH CHECK (is_super_admin());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'uptime_events' AND policyname = 'service_role_insert_uptime_events'
  ) THEN
    CREATE POLICY service_role_insert_uptime_events
      ON public.uptime_events
      FOR INSERT
      TO service_role
      WITH CHECK (true);
  END IF;
END
$$;