/**
 * src/lib/__tests__/dsr-tables.test.ts — A62 DSR foundation parity test.
 *
 * Tripwire that fails CI if the typed DSR catalog drifts from the JSON
 * inventory generated by `scripts/scan-pii-columns.mjs`. The intended
 * remediation when this test fails is always:
 *
 *   1. Re-run `node scripts/scan-pii-columns.mjs` to refresh the JSON.
 *   2. Regenerate `src/lib/compliance/dsr-tables.ts` from the JSON.
 *   3. Re-run `node scripts/scan-pii-columns.mjs --check` locally.
 *   4. Update `docs/compliance/pii-column-inventory.md` headline numbers
 *      to match the new JSON.
 *
 * The test does NOT mutate state and does NOT depend on Supabase or any
 * runtime binding — it is pure data integrity.
 */

import { describe, it, expect } from "vitest";

import inventory from "../../../docs/compliance/_generated/pii-columns.json";
import {
  ALL_DSR_TABLES,
  ARTICLE_9_DSR_TABLES,
  DSR_TABLE_COUNT,
  ERASURE_ANONYMISE_INSTEAD,
  FAMILY_SCOPE_TABLES,
  PATIENT_SCOPE_TABLES,
  TOMBSTONE_USER_SENTINEL,
  USER_RECTIFICATION_ALLOWED_COLUMNS,
  USER_SCOPE_TABLES,
  shouldAnonymiseOnErasure,
  type Article9Category,
  type DsrTable,
} from "../compliance/dsr-tables";

// ---------------------------------------------------------------------------
// Inventory derivation (mirrors the codegen in scripts/scan-pii-columns.mjs)
// ---------------------------------------------------------------------------

type Inventory = typeof inventory;
type Markers = Inventory["markers"];

const markers = inventory.markers as Markers;
const article9Json = inventory.article_9 as Record<string, string[]>;
const dsrScopeJson = inventory.dsr_scope as string[];

function hasMarker(table: string, marker: string): boolean {
  const list = (markers as Record<string, string[]>)[table];
  return Array.isArray(list) && list.includes(marker);
}

const expectedPatientTables = dsrScopeJson.filter((t) => hasMarker(t, "patient_id")).sort();
const expectedUserOnlyTables = dsrScopeJson
  .filter((t) => hasMarker(t, "user_id") && !hasMarker(t, "patient_id"))
  .sort();
const expectedFamilyTables = dsrScopeJson.filter((t) => hasMarker(t, "primary_user_id")).sort();

const expectedArticle9Union = new Set<string>();
for (const tables of Object.values(article9Json)) {
  for (const t of tables) expectedArticle9Union.add(t);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("dsr-tables — JSON inventory parity (A62)", () => {
  it("PATIENT_SCOPE_TABLES matches dsr_scope ∩ has(patient_id)", () => {
    const actual = PATIENT_SCOPE_TABLES.map((t) => t.name).sort();
    expect(actual).toStrictEqual(expectedPatientTables);
    expect(PATIENT_SCOPE_TABLES.every((t) => t.key === "patient_id")).toBe(true);
  });

  it("USER_SCOPE_TABLES matches dsr_scope ∩ has(user_id) \\ has(patient_id)", () => {
    const actual = USER_SCOPE_TABLES.map((t) => t.name).sort();
    expect(actual).toStrictEqual(expectedUserOnlyTables);
    expect(USER_SCOPE_TABLES.every((t) => t.key === "user_id")).toBe(true);
  });

  it("FAMILY_SCOPE_TABLES matches dsr_scope ∩ has(primary_user_id)", () => {
    const actual = FAMILY_SCOPE_TABLES.map((t) => t.name).sort();
    expect(actual).toStrictEqual(expectedFamilyTables);
    expect(FAMILY_SCOPE_TABLES.every((t) => t.key === "primary_user_id")).toBe(true);
  });

  it("ALL_DSR_TABLES equals the concatenation of the three scope arrays", () => {
    expect(ALL_DSR_TABLES.length).toBe(
      PATIENT_SCOPE_TABLES.length + USER_SCOPE_TABLES.length + FAMILY_SCOPE_TABLES.length,
    );
    expect(DSR_TABLE_COUNT).toBe(ALL_DSR_TABLES.length);
  });

  it("DSR_TABLE_COUNT matches inventory.headline.dsr_scope", () => {
    // The headline counts unique tables; the module concatenates by access key.
    // A table appearing only via patient_id is counted once in both.
    const headlineDsrScope = inventory.headline.dsr_scope;
    const uniqueModuleTables = new Set(ALL_DSR_TABLES.map((t) => t.name));
    expect(uniqueModuleTables.size).toBe(headlineDsrScope);
  });

  it("ARTICLE_9_DSR_TABLES equals dsr_scope ∩ article_9 union", () => {
    const actual = new Set(ARTICLE_9_DSR_TABLES.map((t) => t.name));
    const expected = new Set(dsrScopeJson.filter((t) => expectedArticle9Union.has(t)));
    expect(actual).toStrictEqual(expected);
  });
});

describe("dsr-tables — invariants", () => {
  it("every table name is unique across the three scope arrays", () => {
    const names = ALL_DSR_TABLES.map((t) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it("every article9 value is a valid Article9Category", () => {
    const valid: Article9Category[] = [
      "core_phi",
      "mental_health",
      "reproductive_sexual",
      "physical_health_invasive",
      "imaging_phi",
      "genetic_biometric",
    ];
    for (const t of ALL_DSR_TABLES) {
      if (t.article9 !== null) {
        expect(valid).toContain(t.article9);
      }
    }
  });

  it("ERASURE_ANONYMISE_INSTEAD only references known tables in the inventory", () => {
    const known = new Set<string>(Object.keys(markers));
    for (const t of ERASURE_ANONYMISE_INSTEAD) {
      expect(known.has(t), `${t} should appear in inventory.markers`).toBe(true);
    }
  });

  it("shouldAnonymiseOnErasure agrees with the ERASURE_ANONYMISE_INSTEAD list", () => {
    for (const t of ERASURE_ANONYMISE_INSTEAD) {
      expect(shouldAnonymiseOnErasure(t)).toBe(true);
    }
    expect(shouldAnonymiseOnErasure("appointments")).toBe(false);
    expect(shouldAnonymiseOnErasure("medical_records")).toBe(false);
  });

  it("USER_RECTIFICATION_ALLOWED_COLUMNS only lists basic identity fields", () => {
    // Defensive: clinical fields must not slip in. The list is intentionally
    // narrow because clinical rectification requires a doctor, not the patient.
    const forbidden = ["diagnosis", "notes", "content", "role", "auth_id"];
    for (const col of forbidden) {
      expect(USER_RECTIFICATION_ALLOWED_COLUMNS).not.toContain(col);
    }
  });

  it("TOMBSTONE_USER_SENTINEL is a syntactically valid UUID", () => {
    expect(TOMBSTONE_USER_SENTINEL).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
    );
  });

  it("DsrTable type is exported and structurally correct", () => {
    // Compile-time check by virtue of imports; this run-time check guards
    // against an empty catalog regressing to `unknown[]`.
    const head: DsrTable | undefined = ALL_DSR_TABLES[0];
    expect(head).toBeDefined();
    expect(typeof head?.name).toBe("string");
    expect(["patient_id", "user_id", "primary_user_id"]).toContain(head?.key);
  });
});

describe("dsr-tables — sanity floors (prevent silent reductions)", () => {
  // These floors protect against an accidental deletion that empties a scope
  // without anyone noticing. They are deliberately conservative — raise as the
  // schema grows.
  it("has at least 80 patient-scope tables", () => {
    expect(PATIENT_SCOPE_TABLES.length).toBeGreaterThanOrEqual(80);
  });

  it("has at least 30 Article 9 tables in DSR scope", () => {
    expect(ARTICLE_9_DSR_TABLES.length).toBeGreaterThanOrEqual(30);
  });
});
